version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - app:/usr/src/app
    ports:
      - "8000:8000"
    
    env_file:
      - ./.env.dev
  database:
    image: 'postgres:14.1-alpine'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hello_django_dev

volumes:
  app:
  db: